SELECT YEAR, MONTH, U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS
FROM (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH,USER_ID
    FROM ONLINE_SALE 
) AS YM
JOIN USER_INFO U ON YM.USER_ID = U.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, U.GENDER
ORDER BY YEAR, MONTH, U.GENDER