SELECT PR.PRODUCT_ID, PR.PRODUCT_NAME, SUM(FO.AMOUNT * PR.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT PR
JOIN FOOD_ORDER FO ON PR.PRODUCT_ID = FO.PRODUCT_ID
WHERE FO.PRODUCE_DATE LIKE '2022-05%'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PR.PRODUCT_ID