SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM (
    SELECT U.USER_ID, U.NICKNAME, B.PRICE
    FROM USED_GOODS_BOARD B
    JOIN USED_GOODS_USER U ON B.WRITER_ID = U.USER_ID
    WHERE B.STATUS = 'DONE'
    ) AS UB
GROUP BY USER_ID
HAVING SUM(PRICE) >= '700000'
ORDER BY 3 ASC