SELECT I.ID AS ID, INF.FISH_NAME AS FISH_NAME, I.LENGTH AS LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO INF
ON I.FISH_TYPE = INF.FISH_TYPE
WHERE (I.FISH_TYPE, I.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY I.ID