SELECT SCORE, HRGRADE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE 
    WHERE YEAR = '2022'
    GROUP BY EMP_NO
) AS HRGRADE
JOIN HR_EMPLOYEES 
ON HRGRADE.EMP_NO = HR_EMPLOYEES.EMP_NO
ORDER BY SCORE DESC
LIMIT 1