WITH DEPT_SAL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
    FROM HR_EMPLOYEES 
    GROUP BY DEPT_ID
)
SELECT D.DEPT_ID, D.DEPT_NAME_EN, DS.AVG_SAL
FROM HR_DEPARTMENT D
JOIN DEPT_SAL DS ON D.DEPT_ID = DS.DEPT_ID
ORDER BY 3 DESC